version: '2'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - webapi
      - frontend
  
  frontend:
    image: metal3d/ng
    command: serve --host 0.0.0.0
    ports:
    - 4200:4200
    - 49152:49152
    user: 1000:1000
    volumes:
    - ./frontend:/project

  webapi:
    build: ./webapi
    ports:
      - "5000:5000"